CREATE TABLE IF NOT EXISTS product (
	id         SERIAL NOT NULL
		CONSTRAINT product_pkey
			PRIMARY KEY,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	name       TEXT   NOT NULL,
	is_deleted BOOLEAN DEFAULT FALSE
);